// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9NrsNS3O8akHqF12ZXKgatkGqodWGrE',
    appId: '1:341692543128:web:b99679982e3d6d7c3460ed',
    messagingSenderId: '341692543128',
    projectId: 'okter-7f509',
    authDomain: 'okter-7f509.firebaseapp.com',
    databaseURL: 'https://okter-7f509-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'okter-7f509.appspot.com',
    measurementId: 'G-ZMK6D55TTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzs7TI9TNouJYBmSsHL3k0p1_7PnqiPv4',
    appId: '1:341692543128:android:36b08859f5b88ed83460ed',
    messagingSenderId: '341692543128',
    projectId: 'okter-7f509',
    databaseURL: 'https://okter-7f509-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'okter-7f509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpK0q1kLLICW8YiB7WVd7lBV6AvwWXEY',
    appId: '1:341692543128:ios:7c0970150a6fa5ce3460ed',
    messagingSenderId: '341692543128',
    projectId: 'okter-7f509',
    databaseURL: 'https://okter-7f509-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'okter-7f509.appspot.com',
    iosClientId: '341692543128-r3kouoshd3i0b5e22lf28bitirpit960.apps.googleusercontent.com',
    iosBundleId: 'com.example.okter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMpK0q1kLLICW8YiB7WVd7lBV6AvwWXEY',
    appId: '1:341692543128:ios:7c0970150a6fa5ce3460ed',
    messagingSenderId: '341692543128',
    projectId: 'okter-7f509',
    databaseURL: 'https://okter-7f509-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'okter-7f509.appspot.com',
    iosClientId: '341692543128-r3kouoshd3i0b5e22lf28bitirpit960.apps.googleusercontent.com',
    iosBundleId: 'com.example.okter',
  );
}
